

export const ACTION_LABEL: Record<string, string> = {
  CREATE_INFRASTRUCTURE_COST: 'Costo de infraestructura registrado',
  UPDATE_INFRASTRUCTURE_COST: 'Costo de infraestructura corregido',
  UPDATE_PLATFORM_STAFF: 'Permisos internos actualizados',
  ACTIVATE_PLATFORM_SECURITY: 'Control de permisos actualizado',
  DESIGNATE_PLATFORM_PRINCIPAL: 'Administrador principal designado',
  REQUEST_PLATFORM_EXCEPTION: 'Excepción solicitada',
  DECIDE_PLATFORM_EXCEPTION: 'Excepción decidida',
  CREATE_ORGANIZATION: 'Organización creada',
  UPDATE_PLAN: 'Plan cambiado',
  UPDATE_LIMITS: 'Cupos ajustados',
  IMPERSONATE: 'Entró como',
  UPDATE_OSINT_SOURCE: 'Fuente OSINT editada',
  CREATE_OSINT_SOURCE: 'Fuente OSINT publicada',
  REGISTER_PAYMENT: 'Pago registrado',
  VOID_PAYMENT: 'Pago anulado',
  SET_PERIOD: 'Vigencia otorgada',
  CANCEL_SUBSCRIPTION: 'Suscripción cancelada',
  REACTIVATE_SUBSCRIPTION: 'Suscripción reactivada',
  SUBSCRIPTION_STATE_CHANGED: 'Cambio de estado',
  PAY_COMMISSION_INSTALLMENT: 'Comisión pagada',
  ORGANIZATION_DATA_EXPORTED: 'Datos exportados',
  PASSWORD_RESET_LINK_CREATED: 'Enlace de recuperación',
  UPDATE_WHATSAPP_BOT: 'WhatsApp no oficial',
  UPDATE_COMMERCIAL_PLAN: 'Plan comercial editado',
  UPDATE_SALES_LEAD: 'Interesado actualizado',
  CREATE_MANAGEMENT: 'Gestión registrada',
  UPDATE_MANAGEMENT: 'Gestión actualizada',
};
