'use client';
import Link from 'next/link';
import { useCallback, useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { confirmDialog } from '@/components/ui/confirm-dialog';
import { QuerySection } from './query-section';
import { usePlatformCapability } from './access-context';
import { listManagementOperators } from '@/lib/api/platform-management';
import { extractErrorMessage } from '@/lib/api/platform';
import { EXCEPTION_KIND, EXCEPTION_STATUS, listPlatformExceptions, requestPlatformException, decidePlatformException, type PlatformException } from '@/lib/api/platform-access';
const date = (value: string) => new Date(value).toLocaleString('es-CO', { timeZone: 'America/Bogota' });

export function ExceptionsBoard({ organizationId }: { organizationId?: string }) {
  const canRequest = usePlatformCapability('EXCEPTION_REQUEST');
  const canDecide = usePlatformCapability('EXCEPTION_APPROVE');
  const [status, setStatus] = useState('PENDING');
  const [page, setPage] = useState(1);
  const [revision, setRevision] = useState(0);
  const [creating, setCreating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deciding, setDeciding] = useState<PlatformException | null>(null);
  const load = useCallback(() => listPlatformExceptions(new URLSearchParams({ page: String(page), pageSize: '20', ...(status ? { status } : {}) }), organizationId), [page, status, organizationId]);
  return <div className="space-y-4">
    <p className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm">La autorización registra una decisión. La activación del beneficio requiere el flujo comercial correspondiente; todavía no está disponible desde esta solicitud.</p>
    <div className="flex flex-wrap gap-3"><select aria-label="Estado de excepción" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className="rounded-md border p-2"><option value="">Todos</option>{Object.entries(EXCEPTION_STATUS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><Button variant="outline" onClick={() => setRevision((n) => n + 1)}>Actualizar</Button>{canRequest && organizationId && <Button onClick={() => { setCreating(true); setDeciding(null); }}>Solicitar excepción</Button>}</div>
    {creating && organizationId && <QuerySection title="Solicitud de excepción" load={listManagementOperators}>{(operators) => <form className="grid gap-3 rounded-lg border p-4 sm:grid-cols-2" onSubmit={async (event) => {
      event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true);
      try { await requestPlatformException(organizationId, { kind: String(data.get('kind')), reason: String(data.get('reason')).trim(), scope: String(data.get('scope')).trim(), evidence: String(data.get('evidence')).trim(), responsibleId: String(data.get('responsibleId')), expiresAt: new Date(`${data.get('expiresAt')}:00-05:00`).toISOString() }); toast.success('Solicitud registrada, pendiente de aprobación'); setCreating(false); setRevision((n) => n + 1); } catch (error) { toast.error(extractErrorMessage(error)); } finally { setSaving(false); }
    }}><label className="text-sm">Tipo<select name="kind" className="block w-full rounded-md border p-2">{Object.entries(EXCEPTION_KIND).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-sm">Responsable<select name="responsibleId" required className="block w-full rounded-md border p-2"><option value="">Seleccionar</option>{operators.map((op) => <option key={op.id} value={op.id}>{op.fullName}</option>)}</select></label><label className="text-sm sm:col-span-2">Motivo<Input name="reason" required minLength={3} maxLength={1000} /></label><label className="text-sm sm:col-span-2">Condiciones solicitadas<textarea name="scope" required minLength={3} maxLength={5000} className="block min-h-24 w-full rounded-md border p-2" placeholder="Describe módulos, cantidades, importe o cobertura solicitados y sus condiciones." /></label><label className="text-sm sm:col-span-2">Referencia del acuerdo o documento de respaldo<Input name="evidence" required minLength={3} maxLength={2000} /></label><label className="text-sm">Vence (hora de Colombia)<Input name="expiresAt" type="datetime-local" required /></label><div className="flex gap-2 sm:col-span-2"><Button disabled={saving}>Registrar solicitud</Button><Button type="button" variant="outline" disabled={saving} onClick={() => setCreating(false)}>Cancelar</Button></div></form>}</QuerySection>}
    {deciding && canDecide && <form className="space-y-3 rounded-lg border p-4" onSubmit={async (event) => {
      event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true);
      const decision = String(data.get('decision')); const reason = String(data.get('reason')).trim();
      try { if (!await confirmDialog({ title: decision === 'APPROVE' ? 'Autorizar solicitud' : decision === 'REJECT' ? 'Rechazar solicitud' : 'Revocar autorización', description: `${deciding.organization.name}. Condiciones: ${deciding.scope}. Vence: ${date(deciding.expiresAt)}. Motivo: ${reason}. Esta decisión no modifica el servicio contratado.`, confirmLabel: 'Confirmar decisión' })) return; await decidePlatformException(deciding, { version: deciding.version, decision, reason }); toast.success('Decisión registrada'); setDeciding(null); setRevision((n) => n + 1); } catch (error) { toast.error(extractErrorMessage(error)); } finally { setSaving(false); }
    }}><h3 className="font-semibold">Decidir solicitud de {deciding.organization.name}</h3><select name="decision" className="rounded-md border p-2">{deciding.effectiveStatus === 'PENDING' ? <><option value="APPROVE">Autorizar</option><option value="REJECT">Rechazar</option></> : <option value="REVOKE">Revocar autorización</option>}</select><label className="block text-sm">Motivo de la decisión<Input name="reason" required minLength={3} maxLength={1000} /></label><div className="flex gap-2"><Button disabled={saving}>Revisar decisión</Button><Button type="button" variant="outline" disabled={saving} onClick={() => setDeciding(null)}>Cancelar</Button></div></form>}
    <QuerySection key={revision} title="Solicitudes y autorizaciones" load={load}>{(result) => <><p>{result.total} registros</p>{result.items.length ? <ul className="space-y-3">{result.items.map((task) => <li key={task.id} className="space-y-2 rounded-lg border p-4"><p className="font-semibold">{EXCEPTION_KIND[task.kind]} · {EXCEPTION_STATUS[task.effectiveStatus]}</p>{!organizationId && <Link className="text-primary underline" href={`/platform/organizations/${task.organizationId}`}>{task.organization.name}</Link>}<p className="whitespace-pre-wrap">{task.scope}</p><p className="text-sm">Motivo: {task.reason}</p><p className="text-sm">Solicitante: {task.requestedByEmail} · Responsable: {task.responsibleName}</p><p className="text-sm">Vence: {date(task.expiresAt)} · Respaldo: {task.evidence}</p>{task.decidedByEmail && <p className="text-sm">Decisión: {task.decidedByEmail} · {task.decisionReason}</p>}{task.revokedByEmail && <p className="text-sm">Revocación: {task.revokedByEmail} · {task.revocationReason}</p>}<details><summary className="cursor-pointer text-sm">Condiciones registradas al solicitar</summary><dl className="grid gap-2 pt-2 text-sm sm:grid-cols-2">{task.before ? Object.entries(task.before).map(([key, value]) => <div key={key}><dt>{({ planId: 'Plan de módulos', commercialPlanCode: 'Plan comercial', termMonths: 'Meses', currentPeriodStart: 'Inicio registrado', currentPeriodEnd: 'Fin registrado', cancelledAt: 'Cancelación', smsLimit: 'SMS', emailLimit: 'Correo', whatsappLimit: 'WhatsApp', usersLimit: 'Usuarios', prospectsLimit: 'Contactos', storageGbLimit: 'Almacenamiento (GB)', deepSearchWeeklyLimit: 'Deep Search semanal', roleLimits: 'Cupos por rol', baseQuotas: 'Cupos base' } as Record<string, string>)[key] ?? key}</dt><dd className="break-words">{value === null ? 'Sin registrar' : typeof value === 'object' ? Object.entries(value).map(([k, v]) => `${k}: ${v}`).join(', ') : String(value)}</dd></div>) : <p>Sin suscripción al solicitar.</p>}</dl></details>{canDecide && ['PENDING', 'APPROVED'].includes(task.effectiveStatus) && <Button variant="outline" onClick={() => { setCreating(false); setDeciding(task); }}>Revisar solicitud</Button>}</li>)}</ul> : <p>No hay solicitudes con estos filtros.</p>}<div className="flex items-center gap-3"><Button variant="outline" disabled={page <= 1} onClick={() => setPage((n) => n - 1)}>Anterior</Button><span>Página {page}</span><Button variant="outline" disabled={page * result.pageSize >= result.total} onClick={() => setPage((n) => n + 1)}>Siguiente</Button></div></>}</QuerySection>
  </div>;
}
