'use client';
import { useCallback, useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { confirmDialog } from '@/components/ui/confirm-dialog';
import { QuerySection } from './query-section';
import { usePlatformAccess } from './access-context';
import { extractErrorMessage, searchPlatformOrganizations } from '@/lib/api/platform';
import { getPlatformStaff, updatePlatformStaff, activatePlatformSecurity, type StaffData, type StaffAssignment } from '@/lib/api/platform-access';

function OrganizationPicker({ selected, onChange }: { selected: string[]; onChange: (ids: string[]) => void }) {
  const [q, setQ] = useState(''); const [page, setPage] = useState(1);
  const load = useCallback(() => searchPlatformOrganizations(new URLSearchParams({ q, page: String(page), pageSize: '20' })), [q, page]);
  return <div className="space-y-2"><Input aria-label="Buscar organizaciones para asignar" placeholder="Buscar organización" value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} /><p className="text-sm">{selected.length} organizaciones seleccionadas</p><QuerySection title="Organizaciones asignadas" load={load}>{(result) => <><div className="grid gap-2 sm:grid-cols-2">{result.items.map((org) => <label key={org.id} className="text-sm"><input type="checkbox" checked={selected.includes(org.id)} onChange={(e) => onChange(e.target.checked ? [...selected, org.id] : selected.filter((id) => id !== org.id))} /> {org.name}</label>)}</div><div className="flex gap-2"><Button type="button" variant="outline" disabled={page === 1} onClick={() => setPage((n) => n - 1)}>Anterior</Button><Button type="button" variant="outline" disabled={page * 20 >= result.total} onClick={() => setPage((n) => n + 1)}>Siguiente</Button><Button type="button" variant="outline" onClick={() => onChange([])}>Quitar todas las asignaciones</Button></div></>}</QuerySection></div>;
}
function StaffForm({ operator, data, onSaved }: { operator: StaffData['operators'][number]; data: StaffData; onSaved: () => void }) {
  const [form, setForm] = useState<Omit<StaffAssignment, 'userId'>>(operator.assignment ?? { profiles: [], capabilities: [], organizationIds: [], allOrganizations: false, version: 0 });
  const [saving, setSaving] = useState(false);
  return <form className="space-y-4 rounded-lg border p-4" onSubmit={async (event) => { event.preventDefault(); const reason = String(new FormData(event.currentTarget).get('reason')).trim(); setSaving(true); try { if (!await confirmDialog({ title: `Asignar permisos a ${operator.fullName}`, description: `${form.capabilities.length} acciones. Ámbito: ${form.allOrganizations ? 'todas las organizaciones' : `${form.organizationIds.length} asignadas`}. Motivo: ${reason}.`, confirmLabel: 'Guardar permisos' })) return; await updatePlatformStaff(operator.id, { ...form, reason }); toast.success('Permisos registrados'); onSaved(); } catch (error) { toast.error(extractErrorMessage(error)); } finally { setSaving(false); } }}>
    <h3 className="font-semibold">{operator.fullName} · {operator.email}</h3><p className="text-sm">Los perfiles sugieren acciones; revisa las capacidades y el ámbito antes de guardar.</p><div className="flex flex-wrap gap-4">{Object.keys(data.profiles).map((profile) => <label key={profile} className="text-sm"><input type="checkbox" checked={form.profiles.includes(profile)} onChange={(event) => { const profiles = event.target.checked ? [...form.profiles, profile] : form.profiles.filter((entry) => entry !== profile); setForm((old) => ({ ...old, profiles, capabilities: [...new Set(profiles.flatMap((entry) => data.profiles[entry]))] })); }} /> {({ OPERATIONS: 'Operación', FINANCE: 'Finanzas', SALES: 'Ventas', SUPPORT: 'Soporte' } as Record<string, string>)[profile]}</label>)}</div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(data.catalog).map(([capability, label]) => <label key={capability} className="text-sm"><input type="checkbox" checked={form.capabilities.includes(capability)} onChange={(e) => setForm((old) => ({ ...old, capabilities: e.target.checked ? [...old.capabilities, capability] : old.capabilities.filter((entry) => entry !== capability) }))} /> {label}</label>)}</div><label className="block text-sm"><input type="checkbox" checked={form.allOrganizations} onChange={(e) => setForm((old) => ({ ...old, allOrganizations: e.target.checked }))} /> Acceso al conjunto de organizaciones (incluye dirección comercial)</label>{!form.allOrganizations && <OrganizationPicker selected={form.organizationIds} onChange={(organizationIds) => setForm((old) => ({ ...old, organizationIds }))} />}<label className="block text-sm">Motivo del cambio<Input name="reason" required minLength={3} maxLength={1000} /></label><Button disabled={saving}>Revisar permisos</Button>
  </form>;
}
export function StaffPanel() {
  const access = usePlatformAccess(); const [revision, setRevision] = useState(0); const [selected, setSelected] = useState(''); const [saving, setSaving] = useState(false);
  if (!access?.principal) return <p>La asignación de permisos corresponde al administrador principal.</p>;
  return <QuerySection key={revision} title="Equipo y permisos" load={getPlatformStaff}>{(data) => <div className="space-y-4"><p>Administrador principal: {data.operators.find((operator) => operator.id === data.config.principalUserId)?.email ?? 'Cuenta designada'}</p><p>{data.config.enabled ? 'Los permisos por acción y organización están activos.' : 'Preparación: se conservan los permisos anteriores hasta activar este control.'}</p><p className="text-sm">Al activarlo, los operadores sin asignación perderán acceso a las acciones. Los cambios directos de módulos, cupos y vigencia, las exportaciones completas y «ver como» requerirán sus flujos autorizados, pendientes de conexión.</p><select aria-label="Operador a configurar" value={selected} onChange={(e) => setSelected(e.target.value)} className="rounded-md border p-2"><option value="">Seleccionar operador</option>{data.operators.filter((op) => op.id !== data.config.principalUserId).map((op) => <option key={op.id} value={op.id}>{op.fullName} · {op.email}{op.assignment ? '' : ' · sin asignación'}</option>)}</select>{data.operators.find((op) => op.id === selected) && <StaffForm key={selected} operator={data.operators.find((op) => op.id === selected)!} data={data} onSaved={() => setRevision((n) => n + 1)} />}{!data.config.enabled && <Button disabled={saving} onClick={async () => { setSaving(true); try { if (!await confirmDialog({ title: 'Activar permisos por acción', description: 'Se aplicarán las asignaciones registradas. Los operadores sin asignación y las acciones pendientes de sus controles dejarán de estar disponibles.', confirmLabel: 'Activar controles' })) return; await activatePlatformSecurity({ enabled: true, version: data.config.version, reason: 'Activación confirmada por administrador principal desde panel' }); toast.success('Controles activados. Recarga para actualizar la navegación.'); setRevision((n) => n + 1); } catch (error) { toast.error(extractErrorMessage(error)); } finally { setSaving(false); } }}>Activar controles</Button>}</div>}</QuerySection>;
}
